/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChannelsImport } from './routes/channels'
import { Route as IndexImport } from './routes/index'
import { Route as ChannelsChannelIdImport } from './routes/channels.$channelId'

// Create/Update Routes

const ChannelsRoute = ChannelsImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsChannelIdRoute = ChannelsChannelIdImport.update({
  id: '/$channelId',
  path: '/$channelId',
  getParentRoute: () => ChannelsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsImport
      parentRoute: typeof rootRoute
    }
    '/channels/$channelId': {
      id: '/channels/$channelId'
      path: '/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdImport
      parentRoute: typeof ChannelsImport
    }
  }
}

// Create and export the route tree

interface ChannelsRouteChildren {
  ChannelsChannelIdRoute: typeof ChannelsChannelIdRoute
}

const ChannelsRouteChildren: ChannelsRouteChildren = {
  ChannelsChannelIdRoute: ChannelsChannelIdRoute,
}

const ChannelsRouteWithChildren = ChannelsRoute._addFileChildren(
  ChannelsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteWithChildren
  '/channels/$channelId': typeof ChannelsChannelIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/channels' | '/channels/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/channels' | '/channels/$channelId'
  id: '__root__' | '/' | '/channels' | '/channels/$channelId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/channels"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/channels": {
      "filePath": "channels.tsx",
      "children": [
        "/channels/$channelId"
      ]
    },
    "/channels/$channelId": {
      "filePath": "channels.$channelId.tsx",
      "parent": "/channels"
    }
  }
}
ROUTE_MANIFEST_END */
